### PR TITLE
fix order in extension of options

### PR DESCRIPTION
**Pull request by rompic**
i think target and object are mixed up
https://api.jquery.com/jQuery.extend/

### CODE REVIEW

**Comment by rompic** [comment]
This also looks wrong in the other repos.

**Comment by rompic** [comment]
For me it makes a difference on first load.

**Comment by rompic** [comment]
I think we can even get rid of the @mychart.options=

**Comment by jorgemorgado** [comment]
Nice catch, thanks. I will also update the other charts.

**Pull request merged**
